import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar.jsx";
import { Toaster } from "react-hot-toast";
import { UserProvider } from "@/context/context.js";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "codebuddy",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-800 `}
      >
        <UserProvider>
          <Navbar/>
            {children}
          <Toaster position="bottom-right"></Toaster>
        </UserProvider>

      </body>
    </html>
  );
}
